# configure
image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"  # cache on project level
cache:
  paths:
    - .cache/pip
    - venv/

# common to all scripts
before_script:
  - python -V
  - pip install -U virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -U flit
  - pip install -U pytest
  - pip install -U mypy
  - pip install -U yaqc
  - pip install -U numpy
  - pip install -U yaq-traits
  - pip install ./yaqc
  - pip install ./yaqd-core
  - pip install ./yaqd-fakes

# test stage
mypy:
  stage: test
  script:
    - mypy yaqd-core/yaqd_core
    - mypy yaqc/yaqc
    - mypy yaqd-fakes/yaqd_fakes

entry:
  stage: test
  script:
    - yaqd-fake-continuous-hardware --version
    - yaqd-fake-continuous-hardware -h
    - yaqd-fake-discrete-hardware --version
    - yaqd-fake-discrete-hardware -h

traits:
  stage: test
  script:
    - yaq-traits check yaqd-fakes/yaqd_fakes/fake-continuous-hardware.avpr
    - yaq-traits check yaqd-fakes/yaqd_fakes/fake-discrete-hardware.avpr

.pytest: &pytest
  stage: test
  script:
    - cd tests
    - pytest --junitxml=report.xml
  artifacts:
    reports:
      junit: tests/report.xml
pytest-latest:
  image: python:latest
  <<: *pytest
pytest-3.8:
  image: python:3.8
  <<: *pytest
pytest-3.7:
  image: python:3.7
  <<: *pytest

# deploy stage
pages:
  stage: deploy
  script:
  - pip install -U pdoc
  - pdoc --html yaqyaqd_core --html-dir html --overwrite
  - mv html/yaqd_core public
  artifacts:
    paths:
    - public
  only:
    - tags

flit-yaqc:
  stage: deploy
  script:
    - cd yaqc
    - FLIT_PASSWORD=$YAQC_TOKEN flit publish
  artifacts:
    paths:
      - yaqc/dist/*
  only:
    - tags
    - /^yaqc-.*$/

flit-yaqd-core:
  stage: deploy
  script:
    - cd yaqd-core
    - FLIT_PASSWORD=$YAQD_CORE_TOKEN flit publish
  artifacts:
    paths:
      - yaqd-core/dist/*
  only:
    - tags
    - /^yaqd-core-.*$/

flit-yaqd-fakes:
  stage: deploy
  script:
    - cd yaqd-fakes
    - FLIT_PASSWORD=$YAQD_FAKES_TOKEN flit publish
  artifacts:
    paths:
      - yaqd-fakes/dist/*
  only:
    - tags
    - /^yaqd-fakes-.*$/
