repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        args: [-b, master]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        exclude: ^tests/

default_language_version:
  python: python3
